---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: address
  namespace: address-graphql
spec:
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
    - name: default
      config:
        node.roles:
          - master
          - data
          - ingest
        node.attr.attr_name: attr_value
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: gp2
      podTemplate:
        metadata:
          labels:
            app: address
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 4Gi
                  cpu: 2
                limits:
                  memory: 4Gi
                  cpu: 2
      count: 3
  version: 7.12.1
